[tool.poetry]
name = "equinor-trading-repo-template"
version = "0.1.0"
description = "Standard template containing the essentials for a new repo"
authors = ["Equinor"]

[tool.poetry.dependencies]
python = ">=3.7.1,<3.9"

[tool.poetry.dev-dependencies]
pytest = "^6.2.5"
black = "^21.11b1"
mypy = "^0.910"
isort = "^5.10.1"
flake8 = "^4.0.1"
Sphinx = "^4.3.1"
sphinx-rtd-theme = "^1.0.0"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
